### ISSUE TITLE
Warn about ignoring hints in places where the hint no longer applies.

### ISSUE THREAD

**Issue by NorfairKing** [ndmitchell/hlint#1239]
Suppose I have this file:

```
module Example where

f = (\a -> (a, b)) <$> Nothing
```
I don't like tuplesections here, so I add this to my config:
```
- ignore:
    name: Use tuple-section
    within:
      - Example.f
```
Then I decide `f` should be called `g`.
Now I get the warning again (fine), but I have also accumulated a line in my `.hlint.yaml` that's unlikely to ever be removed.

It would be nice if `hlint` said something like "You have warning X which is ignored in place Y but place Y doesn't exist."
