### ISSUE TITLE
Forbid all functions from module with exceptions

### ISSUE THREAD

**Issue by brandon-leapyear** [ndmitchell/hlint#1244]
I'd like to forbid all functions from `Control.Exception` (requiring using `UnliftIO.Exception`), but I'd like to allow certain imports like `Exception`, where someone might reasonably want to derive `Exception` without wanting to pull in all the `unliftio` dependencies.

I think you can forbid things like
```yaml
- modules:
    - name: Control.Exception
      badidents: [catch, catchJust, handle, handleJust, ...]
```
but it'd be nice to do it the other way
```yaml
- modules:
    - name: Control.Exception
      only: [Exception, SomeException]
```
