### ISSUE TITLE
ignore "Avoid restricted flags" not respected in test/Spec.hs

### ISSUE THREAD

**Issue by JasonMFry** [ndmitchell/hlint#1320]
I suspect this is user error on my part, but I have tried everything I can think of and I'm still getting an hlint error when I don't want to.

```text
test/Spec.hs|1| 1-68: Warning: Avoid restricted flags
|| Found:
||   {-# OPTIONS_GHC -F -pgmF hspec-discover -optF --module-name=Spec #-}
|| Note: may break the code, may break the code, may break the code, may break the code, may break the code
|| 
|| 1 hint
|| make: *** [hlint] Error 1
```

```haskell
-- test/Spec.hs
{-# OPTIONS_GHC -F -pgmF hspec-discover -optF --module-name=Spec #-}
```

```yaml
# .hlint.yaml
- ignore:
    name:
      - Avoid restricted flags
      - Avoid restricted function
      - Avoid restricted module
      - Avoid restricted qualification
    within:
      - "**.*Spec"
      - Spec # I have tried many things here, including Spec.hs, test/Spec.hs, test.Spec.hs, etc etc
```
