### ISSUE TITLE
How are qualified function names matched?

### ISSUE THREAD

**Issue by michaelpj** [ndmitchell/hlint#1389]
I am quite confused about this.

I attempted to warn on use of `head` with
```
- functions:
  - name: Data.List.head
    within: [...]
```
adding exceptions until I got no hints.

But then I tried this, and I got more hints!!

```
- functions:
  - name: Data.List.head
    within: [...]
  - name: Prelude.head
    within: []
```

Okay, so sometimes it matches `Prelude.head` but not `Data.List.head`? What's going on?

For bonus points, I tried to merge the two as follows, but that started giving 0 hints again?

```
- functions
  - name: [Data.List.head, Prelude.head]
    within: [...]
```
