### ISSUE TITLE
`within` changes the behavior of `modules: {as: }`

### ISSUE THREAD

**Issue by parsonsmatt** [ndmitchell/hlint#1615]
We want to gradually become consistent with our naming of `Data.List.NonEmpty`, so we create an `hlint` rule:

```yaml
- modules:
    - name: [Data.List.NonEmpty] 
      as: NE
```

I run `hlint` on our codebase to get all the currently failing examples, and I create a `within` to ignore them:

```yaml
- modules:
    - name: [Data.List.NonEmpty] 
      as: NE
      within: [ ... ]
```

But now it starts complaining about importing `Data.List.NonEmpty` *at all*. It seems like `within` is causing it to ignore the `as:` key.
