### ISSUE TITLE
`modules` without `within` does nothing

### ISSUE THREAD

**Issue by parsonsmatt** [ndmitchell/hlint#1631]
We had an `hlint` rule like this:

```yaml
modules:
  - name: [Network.HTTP.Client]
    message: "Please import OpenTelemetry.Instrumentation.HttpClient instead so that requests may be properly traced."
```

This rule doesn't do anything. The intention was to ban the import of the module. To make it work, we needed to do `within: []`. 

I think it makes sense to infer a `within: []` when it is unspecified. The point of `within` is that it is a list of modules that are opting-out of the rule, and so we are sort of defaulting a missing `within` to `within: **.*` which feels way worse.
