### ISSUE TITLE
Dollar within list literals

### ISSUE THREAD

**Issue by nponeccop** [ndmitchell/hlint#319]
I want to add few custom rules in yaml format and test them. The following rule fires when run on Haskell files:

```yaml
- group:
    name: aaa
    enabled: true
    imports:
    - package base
    rules:
    - warn: {name: my-x, lhs: "[a (b c)]", rhs: "[a $ b c]" }

# <TEST>
# yes = [a (b c)] -- [a $ b c]
# </TEST>
```

But my `<TEST></TEST>` section seems wrong, at least I cannot run it with `hlint test`.

Also the rule offers to replace  `[a $ b c]` with  `[a $ b c]`.
