### ISSUE TITLE
"ignore: {}" causes restricted functions and imports to be ignored

### ISSUE THREAD

**Issue by langston-barrett** [ndmitchell/hlint#748]
In HLint 2.2.2, the following config:
```yaml
- ignore: {}
- functions:
  - {name: putStrLn, within: []}
- modules:
  - {name: [Data.List], as: List}
```
causes no warning to be issued on the following module:
```haskell
module Main where
import Data.List as L
main :: IO ()
main = putStrLn $ L.intercalate " " ["hlint", "is", "awesome"]
```
whereas the appropriate warnings are raised without the `ignore: {}`. This is counterintuitive to me, because the README says:
> These directives are applied in the order they are given, with later hints overriding earlier ones.
