### ISSUE TITLE
Invalid suggestion (type incorrect)

### ISSUE THREAD

**Issue by LeventErkok** [ndmitchell/hlint#980]
This started happening recently:

```
$ cat a.hs
infixl 8 ^.
a ^. b = error "undefined"

t a = a ^. 1 ^. 1
```

```
$ hlint --version
HLint v2.2.11, (C) Neil Mitchell 2006-2020
$ hlint a.hs
a.hs:4:11: Warning: Use .
Found:
  a ^. 1 ^. 1
Perhaps:
  a ^. (1 . 1)

1 hint
```
The suggestion doesn't type check.

Perhaps its a breakage in an upstream tool? (Looks like maybe the parser is doing something funky that throws hlint off.) Happy to provide more details.

**Comment by googleson78** [comment]
The default `lens` group is "at fault":
```yaml
- group:
    name: lens
    enabled: true
    imports:
    - package base
    - package lens
    rules:
    - warn: {lhs: "(a ^. b) ^. c", rhs: "a ^. (b . c)"}
```

**Comment by googleson78** [comment]
Ok... wat:
```haskell
blademaster :: ~ » cat a.hs
infixl 8 ^.
a ^. b = error "undefined"

t a = a ^. 1 ^. 1
```

With only the group:
```yaml
blademaster :: ~ » cat hlint.yaml
- group:
    name: lens
    enabled: true
    imports:
    - package base
blademaster :: ~ » hlint -h hlint.yaml a.hs
a.hs:4:7-17: Warning: Redundant ^.
Found:
  a ^. 1 ^. 1
Perhaps:
  a ^. (1 . 1)

1 hint
```

but disabling the group disables the hint!:
```yaml
blademaster :: ~ » cat hlint.yaml
- group:
    name: lens
    enabled: false
    imports:
    - package base
blademaster :: ~ » hlint -h hlint.yaml a.hs
No hints
```
